
package org.tempuri;

import javax.xml.ws.WebFault;
import org.datacontract.schemas._2004._07.SealSignDSSService.SealSignDSSFaultContract;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SealSignDSSFaultContract", targetNamespace = "http://schemas.datacontract.org/2004/07/SealSignDSSService")
public class IDistributedSignatureServiceBasicEndSignatureProviderSealSignDSSFaultContractFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SealSignDSSFaultContract faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IDistributedSignatureServiceBasicEndSignatureProviderSealSignDSSFaultContractFaultFaultMessage(String message, SealSignDSSFaultContract faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IDistributedSignatureServiceBasicEndSignatureProviderSealSignDSSFaultContractFaultFaultMessage(String message, SealSignDSSFaultContract faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.datacontract.schemas._2004._07.sealsigndssservice.SealSignDSSFaultContract
     */
    public SealSignDSSFaultContract getFaultInfo() {
        return faultInfo;
    }

}
